### PR TITLE
run.py: Introduce metadata files for results

### PR DESCRIPTION
**Pull request by k0machi**
This commit introduces results metadata files for collecting by argus
scripts within scylla-pkg.

Task: scylladb/argus#289

### CODE REVIEW

**Comment by k0machi** [comment]
@fruch Can't assign myself or set you as the reviewer for this repo, but there's the CPP driver variant

**Comment by k0machi** [comment]
[Jenkins](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/alexey-cpp-driver-matrix-test/25/)

**Comment by fruch** [comment]
> [Jenkins](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/alexey-cpp-driver-matrix-test/25/)

Job didn't found some git branch, why is this using a scylla-pkg from a fork ?

**Comment by k0machi** [comment]
> > [Jenkins](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/alexey/job/alexey-cpp-driver-matrix-test/25/)
> 
> Job didn't found some git branch, why is this using a scylla-pkg from a fork ?

Ah, it was waiting a long time in the queue and I missed that it had the branch for the reporting-rework (I was checking legacy API with this job previously). Restarted with correct repo.

**Review by fruch — COMMENTED** [review]
LGTM

**Pull request merged**
